export const VIETNAMESE_VIDEO = "VIETNAMESE_VIDEO";

export const AMERICAN_VIDEO = "AMERICAN_VIDEO";

export const KOREAN_VIDEO = "KOREAN_VIDEO";

export default {
  VIETNAMESE_VIDEO,
  AMERICAN_VIDEO,
  KOREAN_VIDEO,
};
