export const VIETNAMESE_SONG = "VIETNAMESE_SONG";

export const AMERICAN_SONG = "AMERICAN_SONG";

export const KOREAN_SONG = "KOREAN_SONG";

export default {
  VIETNAMESE_SONG,
  AMERICAN_SONG,
  KOREAN_SONG,
};
