export const ARTIST_LOADING = "ARTIST_LOADING";

export const ARTIST_FETCH = "ARTIST_FETCH";

export const ARTIST_ERROR = "ARTIST_ERROR";

export default {
  ARTIST_LOADING,
  ARTIST_FETCH,
  ARTIST_ERROR,
};
