name: Build and Deploy
on:
  push:
    branches:
      - development
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and Build
        run:
          - npm install
          - npm run storybook-build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: development
          FOLDER: docs-build
          CLEAN: true
          TARGET_FOLDER: docs
