name: Test
on:
  push:
    - dev
jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          npm install
          npm run jest
